# Generated by Django 5.0.1 on 2024-02-11 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Description',
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='book',
            name='OverallRating',
            field=models.FloatField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='SoldQuantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='TotalReviews',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=4096, validators=[django.core.validators.RegexValidator(code='invalid_password_format', message='Password must contain atleast 1 uppercase letter, 1 special character, and 1 number and be atleast 5 characters long.', regex='^(?=.*[A-Z])(?=.*[!@#$%^&*])(?=.*[0-9]).{5,}$')]),
        ),
    ]
